Fix read describe cases
epiverse-trace/tutorials-early pull request #39
Opened 2024-04-01 22:32 UTC by Degoot-AM

This PR aims at addressing existing conflicts with origin before get more complicated. This issues specifically arise from  
including the development version of `{cleanepi}` package. It also adds the following episodes:

1. Read case data [TBC]
2. Clean and validate data [TBC]
3. Aggregate and visualize
4. Early analysis

2024-04-03 15:57 UTC, avallecam commented
@Degoot-AM thank you for requesting a review, I'll be able to do this next week on Friday. Hope this works for you.

2024-04-03 15:59 UTC, avallecam commented
given that all checks have passed, the workbench workflows created a preview branch with the number of the PR [`md-outputs-PR-39`](https://github.com/epiverse-trace/tutorials-early/tree/md-outputs-PR-39)

2024-04-05 02:51 UTC, Karim-Mane approved these changes

2024-04-05 02:51 UTC, Karim-Mane commented on episodes/read-cases.Rmd
> +requireNamespace("DBI", quietly = TRUE)
Is this section not covered by {readepi}?

{readepi} can read from RDBMS and APIs

2024-04-05 11:38 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +In the process of analyzing outbreak data, it's essential to ensure that the dataset is clean, curated,  standardized, and validate to facilitate accurate and reproducible analysis. This episode focu
OK.

2024-04-05 11:38 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +sim_ebola_data <- cleanepi::check_subject_ids(sim_ebola_data,
OK.

2024-04-14 12:47 UTC, avallecam requested changes
Thank you for your contribution @Degoot-AM. Here I share a partial review of the first episode on read data. I'll add a review of the other episodes in a separate review.

Here I highlight specific suggestions and questions that are already in the comments:
- we can use library(package) instead of requireNamespace. This could be extended to all the other episodes too.
- Downloaded data may follow a similar approach as used in other episodes. Also added an example.
- Will content using {readepi} be included in this episode and in this PR or in a separate one?

2024-04-14 12:47 UTC, avallecam commented on episodes/read-cases.Rmd
> +requireNamespace("DBI", quietly = TRUE)
I'm interested to read the rationale behind this decision too

2024-04-14 12:47 UTC, avallecam commented on episodes/read-cases.Rmd
> +requireNamespace("RSQLite", quietly = TRUE)
as suggested above

```suggestion
library(DBI)
library(RSQLite)

```

2024-04-14 12:47 UTC, avallecam commented on episodes/read-cases.Rmd
>  # Store the 'case_data' dataframe as a table named 'cases'
In this chuck, adding a space between each action increases the visibility of each step. We can replicate this in the following lines too (read, close, view)

```suggestion
# Create a temporary SQLite database in memory
db_con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

# Store the 'case_data' dataframe as a table named 'cases'
```

2024-04-14 12:47 UTC, avallecam commented on episodes/read-cases.Rmd
> +-[TBC]
Is this going to be covered in this PR or in a separate one?

2024-04-14 12:47 UTC, avallecam commented on episodes/read-cases.Rmd
> +This code first establishes a connection to an SQLite database created in memory using `dbConnect()`. Then, it writes the `case_data` into a table named 'cases' within the database using the `dbWrite
After learning how to connect with DB's it is useful to learn the rationale behind using SQL queries to optimize local memory usage. I suggest to add a callout and redirect to the {dbplyr} package, which is also used in the datacarpentries episode already linked there.

```suggestion
This code first establishes a connection to an SQLite database created in memory using `dbConnect()`. Then, it writes the `case_data` into a table named 'cases' within the database using the `dbWriteTable()` function. Subsequently, it reads the data from the 'cases' table using `dbReadTable()`. Finally, it closes the database connection with `dbDisconnect()`. More examples about SQL databases and R can be found [here](https://datacarpentry.org/R-ecology-lesson/05-r-and-databases.html).

:::::::::::::::::::::: callout

### Run SQL queries in R using dbplyr

Using a database interface package is invaluable for optimizing memory usage because it can strategically limit the amount of data pulled from the database through queries. By leveraging such a package, one can ensure that most aggregation tasks are performed directly within the database before extracting the necessary information. This approach minimizes the need to load large datasets into local memory for processing, thereby conserving resources and enhancing performance. Conversely, relying solely on external data manipulation processes can lead to suboptimal memory usage. Conducting all data operations outside the database could tax system resources and hinder efficiency.

Read the [Introduction to dbplyr](https://dbplyr.tidyverse.org/articles/dbplyr.html) vignette to learn how to generate your own queries!

::::::::::::::::::::::

```

2024-04-16 08:27 UTC, Degoot-AM commented on episodes/read-cases.Rmd
> +requireNamespace("DBI", quietly = TRUE)
Yes, {readepi} can import data from RDBMS, however,  by the time I wrote this episode this functionality was not full implemented. Later when it is full functional we can update this section. Also, {DBI} allows for creating light in-memory database, which fit our purpose her.

2024-04-16 08:56 UTC, Degoot-AM commented on episodes/read-cases.Rmd
>  You can check the supported file formats in the `{rio}` package as follows:
Thank you.

2024-04-16 09:00 UTC, Degoot-AM commented on episodes/read-cases.Rmd
> +-[TBC]
This will be covered by a separate PR.

2024-04-16 09:06 UTC, Degoot-AM commented on episodes/read-cases.Rmd
> +This code first establishes a connection to an SQLite database created in memory using `dbConnect()`. Then, it writes the `case_data` into a table named 'cases' within the database using the `dbWrite
Thank you for your suggestion.

2024-04-16 12:53 UTC, Degoot-AM commented
>     * we can use library(package) instead of requireNamespace. This could be extended to all the other episodes too.

>  Using library with `package::function()` will cause `lintr` to raise a warning and block merging. I would suggest to use `loadNamespace` instead. What do you think @avallecam

2024-04-17 10:43 UTC, avallecam commented
> Using library with `package::function()` will cause `lintr` to raise a warning and block merging. I would suggest to use `loadNamespace` instead. What do you think @avallecam

Yes, just recall that. Actually, we fixed this in https://github.com/epiverse-trace/tutorials-early/commit/c9954bcaaa42e01aab1053a0f3f5b812fb1a3b41 to avoid warnings. Try keeping this warning in the local version, and pushing this to GitHub. It should pass.

2024-04-18 09:34 UTC, Degoot-AM commented on config.yaml
> +- describe-cases.Rmd
episodes added to the lesson

2024-04-23 13:39 UTC, avallecam reviewed
Nice arrangement of episodes covering a good diversity of packages within this task. My general suggestions go to add spaces within code chunks and brief comments in each action.

The `md-output` shows and `error`, so we need to solve this before merging this branch. I suggest to prioritize comments and create issues from other that may not be so relevant or may require more time. I think it would be possible to merge this PR at the end of this week.

Then, we may need to find how to rearrange the episodes later given that the `describe-cases` episode already uses epiparameter.

2024-04-23 13:39 UTC, avallecam commented on episodes/read-cases.Rmd
> +Using a database interface package is invaluable for optimizing memory usage because it can strategically limit the amount of data pulled from the database through queries. By leveraging such a packa
I think I added this and looks too long. Two sentences may be enough for this.

```suggestion
A database interface package optimize memory usage by processing the database before extraction, reducing memory load. Conversely, conducting all data manipulation outside the database (e.g., in our local Rstudio session) can lead to inefficient memory usage and strained system resources.
```

2024-04-23 13:39 UTC, avallecam commented on episodes/clean-data.Rmd
> +utils::head(raw_ebola_data, 5)
we can provide space and brief descriptions

```suggestion
# Load packages
library("rio")
library("here")

# Read data
raw_ebola_data <- rio::import(
  here::here("built", "data", "simulated_ebola_2.csv")
)

# Return first five rows
utils::head(raw_ebola_data, 5)
```

2024-04-23 13:39 UTC, avallecam commented on episodes/clean-data.Rmd
> +sim_ebola_data$case_id <- as.character(sim_ebola_data$case_id)
Two lines increase readability

```suggestion
# remove this chunk code once {cleanepi} is updated. 
# The coercion made here will be accounted for within {cleanepi}
sim_ebola_data$case_id <- as.character(sim_ebola_data$case_id)
```

2024-04-23 13:39 UTC, avallecam commented on episodes/describe-cases.Rmd
> +library("simulist")
nice usage of {simulist} to showcase data aggregation. I suggest adding brief descriptions of each step and separating them with spaces, as suggested in other chunks.

2024-04-23 13:39 UTC, avallecam commented on episodes/simple-analysis.Rmd
>  ## Simple model
possibly here we can add a bit on the limits of log-linear models? like in this slides, but less mathy? https://www.reconlearn.org/slides/outbreak-statistics/outbreak-statistics#31 (but this comment is a good candidate to leave for a issue to assess later in a separate branch)

2024-04-25 14:25 UTC, Degoot-AM commented on episodes/read-cases.Rmd
> +case_data <- rio::import(here::here("built", "data", "ebola_cases.csv"))
Good point. Thanks.

2024-04-25 14:48 UTC, Degoot-AM commented on episodes/read-cases.Rmd
> +rio::import(here::here("some", "where", "downto", "path", "file_name.zip"))
Ok. I have a Marburg outbreak data set to the data.

2024-04-26 08:38 UTC, Degoot-AM commented on episodes/simple-analysis.Rmd
>  ## Simple model
created issue to address this point.

2024-04-26 08:56 UTC, Degoot-AM commented on episodes/describe-cases.Rmd
> +library("simulist")
Thank you.

2024-04-27 19:30 UTC, Degoot-AM reviewed
first submit for early tutorials.

2024-04-29 20:11 UTC, avallecam approved these changes
This PR is now ready to merge 🚀 

I fixed the errors visible in the `md-outputs-PR` in this commit https://github.com/epiverse-trace/tutorials-early/pull/39/commits/1f956a0c84ff340eb49a447d404922e24b2f90f2 I followed the template in this previous reading step https://github.com/epiverse-trace/tutorials-early/blob/fabe4f0925e30734d76eb85c884f7b48544917db/episodes/delays-functions.Rmd#L559-L570 

We should not use here::here() to read data in the workbench, instead we use `file.path()`, but we can suggest the reader to use it. 

A way to verify this is by running the chunks locally, getting outputs like these

## With error:
![Screenshot 2024-04-29 193824](https://github.com/epiverse-trace/tutorials-early/assets/21230390/4a7d23c3-1ea9-4a81-8d5f-9d5c9778add0)

## Fixed:
![Screenshot 2024-04-29 193845](https://github.com/epiverse-trace/tutorials-early/assets/21230390/cc5d9390-23ef-4ccf-b23b-fa03490df395)

2024-04-29 21:21 UTC, merged