add read delays episode
epiverse-trace/tutorials-early pull request #5
Opened 2024-02-20 19:49 UTC by avallecam

This PR covers https://github.com/epiverse-trace/tutorials/pull/104#issuecomment-1915079194

I'll appreciate your specific feedback providing a clear next step to remove, change or add content. 

Some questions to guide this are:

- Should we cut the episode on "read delays" in two or three? Where? (possibly between [continuous distribution](https://github.com/epiverse-trace/tutorials/blob/md-outputs-PR-104/read-delays.md#continuous-distributions) and [Adjusting for reporting delays](https://github.com/epiverse-trace/tutorials/blob/md-outputs-PR-104/read-delays.md#adjusting-for-reporting-delays))
- Should we add and adapt the {epiparameter} concept map as in [#103](https://github.com/epiverse-trace/tutorials/issues/103)?

How to review?

- follow the steps in the [reviewer role section of the contributing.md file](https://github.com/epiverse-trace/tutorials-early/blob/main/CONTRIBUTING.md#reviewer)
- if local rendering doesn't work, please, report them in Issues.
- you can read online the knitted content of this PR in branch `md-output-#` (to link after checks pass) (drawback, figure captions not visible)

About local rendering issues:
- https://github.com/epiverse-trace/tutorials/issues/39
- https://github.com/epiverse-trace/tutorials/issues/115

2024-02-24 14:54 UTC, avallecam commented
@CarmenTamayo @joshwlambert could we have your review during the coming week?

2024-02-26 14:56 UTC, joshwlambert commented
@avallecam please can you confirm this is a partial package review? The PR is targeting the `only-middle-late` branch which is far behind `main`. Is this to provide more git diffs for review or should this PR be targeting `main`?

2024-02-26 15:46 UTC, avallecam commented
> @avallecam please can you confirm this is a partial package review? The PR is targeting the `only-middle-late` branch which is far behind `main`. Is this to provide more git diffs for review or should this PR be targeting `main`?

yes, I confirm this is a partial review (plus additional commits ahead of `main`). The final aim of this PR is to redirect `add-read-delays` to `main`.

2024-02-26 15:53 UTC, avallecam commented
I notify that I'll need to fix #4 before reviews. I confirmed this earlier as briefly reported in https://github.com/epiforecasts/EpiNow2/issues/581. I'll change this to draft to solve this now.

2024-02-26 15:55 UTC, joshwlambert commented
> I notify that I'll need to fix https://github.com/epiverse-trace/tutorials-early/issues/4 before reviews. I confirmed this earlier as briefly reported in https://github.com/epiforecasts/EpiNow2/issues/581. I'll change this to draft to solve this now.

@avallecam I've already started the review, therefore I would appreciate, if you left any changes and leaving this PR live until after I've submitted the review.

2024-02-26 16:00 UTC, avallecam commented
> @avallecam I've already started the review, therefore I would appreciate, if you left any changes and leaving this PR live until after I've submitted the review.

got it. sorry, I was not aware this could generate this inconvenience. then, I'll wait until your review, I'll be able to deal with #4 later.

2024-02-26 16:44 UTC, joshwlambert requested changes
Thanks for tagging for review. I enjoyed reading through the material and it's well laid out and informative. I think it reads well for those new to outbreak analytics and to R programming. 

A general question, have you checked that all the images you are using from papers are allowed to be used with only attribution? I checked one or two and they seemed fine, butI didn't check every figure as there are many. 

I'm not sure if it's possible with the current setup/infrastructure, but it would be good if you cited the papers mentioned using a bibliography and then provided a references section at the bottom of each page (as Epiverse vignettes do). They can also be hyperlinked as they are now.

Getting an {EpiNow2} developer to also check code chunks that use that package would be good, as I'm not familiar with the methods in that package and how best to call the `epinow()` function.

If any of my comments are unclear please feel free to respond to them and I will clarify.

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-reuse.Rmd
> +```
To answer one of your questions from the pull request description:

> Should we use partial words like "serial" instead of "serial interval" for epidist_db()?

I personally do not have a preference. {epiparameter} is setup to be flexible and accept both. If we are following the code standard of no partial matching then it might be best to specify in full as `generation time`. The downside of this is that is will not match database entries called `generation interval` or `generation period` so perhaps leaving as `generation` is best. I'll let you make the decision.

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-reuse.Rmd
> +With this query combination, we get more than one delay distribution. This output is an object class `<multi_epidist>`.
I'm not sure we need to mention the `<multi_epidist>` class. This is only in {epiparameter} to improve printing for long lists and does not have any functional purpose, so it may confuse learners more than help them.

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-reuse.Rmd
> +With this query combination, we get more than one delay distribution. This output is an object class `<multi_epidist>`.
Instead you can just describe it as a list of `<epidist>` objects.

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-reuse.Rmd
> +- Then, the parameterised`⁠<epidist>`⁠ with the largest sample size will be returned.
I think these should be the same bullet point.

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-reuse.Rmd
> +What does a parametrised `<epidist>` is? Look at `?is_parameterised`.
This question needs rewording. What about "What is a parameterised `<epidist>`?"

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-reuse.Rmd
> +- Use `{epiparameter}` to access the systematic review catalogue of epidemiological delay distributions.
Same comment as above about systematic reviews.

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-functions.Rmd
> +- How to connect reused delays with my existing analysis pipeline?
Do you mean "reusable" rather than "reused"? Or "How to reuse delays stored in the `{epiparameter}` library with my existing analysis pipeline?"

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-functions.Rmd
> +**Epidemic theory** : Epidemiological parameters. Time periods.
Same comment as before on using a comma-separated list.

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-functions.Rmd
> +Now, we have an epidemiological parameter we can reuse! We can replace the **summary statistics** numbers we plug into `EpiNow2::dist_spec()`.
```suggestion
Now, we have an epidemiological parameter we can reuse! We can replace the **summary statistics** we plug into `EpiNow2::dist_spec()`.
```

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-functions.Rmd
> +library(tidyverse)
Which {tidyverse} packages are being used in this page? If just the pipe (`%>%`) then I recommend calling `library(magrittr)`.

2024-02-26 16:44 UTC, joshwlambert commented on episodes/delays-functions.Rmd
> +In the `epiparameter::list_distributions()` output, we can also find different types of probability distributions (e.g., Log-normal, Weibull, Normal).
Maybe good to add some explanation here that {epiparameter} uses the base R naming convention for distributions. This is why Lognormal is called `lnorm`.

2024-03-20 13:11 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +- Get delays from a systematic review with `{epiparameter}`.
Thank you for the specific suggestion. I'm interested to express then somewhere the line of "Such distributions will enable outbreak analysts to easily access these distributions for routine analysis". I'll look where it fits.

```suggestion
- Get delays from literature searches with `{epiparameter}`.
```

2024-03-20 19:40 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +- Get delays from a systematic review with `{epiparameter}`.
replaced all terms in text in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/f6d1dbe3b4e2ae2f72d08ddb59bea07fabdab85d

2024-03-20 19:47 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +**Epidemic theory** : Epidemiological parameters. Time periods.
Agree. For homogeneity across currently [online tutorials](https://epiverse-trace.github.io/tutorials-late/simulating-transmission.html#prerequisites), I'll use commas.

```suggestion
**Epidemic theory** : Epidemiological parameters, time periods.
```

2024-03-20 19:51 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +The [natural history](../learners/reference.md#naturalhistory) of an infectious disease shows that its development has a regularity from stage to stage. The time periods from an infectious disease in
fixed in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/dd47ea823898638bdf9cb135f75b0a5871116546

2024-03-20 19:58 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +However, early in an epidemic, modelling efforts can be delayed by the lack of a centralised resource that summarises input parameters for the disease of interest ([Nash et al., 2023](https://mrc-ide
> It's fine to describe {epireview} as a systematic review as they are following a systematic protocol, however, same comment as above for {epiparameter} to rephrase systematic review.

Edited as "literature synthesis protocols" as a general reference to both in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/f6d1dbe3b4e2ae2f72d08ddb59bea07fabdab85d

Also used the proposed rephrase in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/87694a425302b5a14e52d0e7a9837db847ab6c04

2024-03-21 13:06 UTC, avallecam commented on episodes/delays-functions.Rmd
> +In the `epiparameter::list_distributions()` output, we can also find different types of probability distributions (e.g., Log-normal, Weibull, Normal).
added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/e46d3aafc30214058f2d9de97b16748fb6b5754f

2024-03-21 18:31 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +To exemplify how to use `{epiparameter}` in your analysis pipeline, our goal in this episode will be to replace the `generation_time` input that we can use for `EpiNow2::epinow()`.
Thanks for writing your main reason to use {epiparameter}. I emphasized the contrast between choosing within the analysis code against copy/pasting reported values on paper. Added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/dcfc264d4cf5cbe644c97acfeaee6cd48bbfb920

2024-03-21 19:36 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +To exemplify how to use `{epiparameter}` in your analysis pipeline, our goal in this episode will be to replace the `generation_time` input that we can use for `EpiNow2::epinow()`.
I opt not to show `epinow()` or `generation_times` yet in the first episode. We plan to show episodes in this order: `delays-reuse`, [`quantify-transmissibility`](https://epiverse-trace.github.io/tutorials-middle/quantify-transmissibility.html), `delays-functions`.

2024-03-21 19:42 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +To do this replacement, instead of plug-in numeric values to `EpiNow2::dist_spec()` to manually specify the **summary statistics** of the delay distribution, we are going to collect them from the lib
this now looks differently ([read the `md-output-PR`](https://github.com/epiverse-trace/tutorials-early/blob/md-outputs-PR-5/delays-reuse.md#the-problem)) and possibly with less ambiguity.

2024-03-21 19:50 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +library(tidyverse)
Added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/ee7846c919376fb6b7ca4cd3d408d08f08d75f31

2024-03-21 19:52 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +However, using the *serial interval* as an approximation of the *generation time* is primarily valid for diseases in which infectiousness starts after symptom onset ([Chung Lau et al. 2021](https://a
Added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/3baf6734702ba6800ccadc0c2ee1dfe41259b47d

2024-03-21 19:58 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +```
I'll keep it with partial matching.

2024-03-21 20:04 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +With this query combination, we get more than one delay distribution. This output is an object class `<multi_epidist>`.
added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/96d0ec8ce2c5487c8dae39a55d1bb9f43b84e754

2024-03-21 20:08 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +- Then, the parameterised`⁠<epidist>`⁠ with the largest sample size will be returned.
added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/a33b7d3553b767a569e6b306e3a3d553debfd787

2024-03-21 20:10 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +What does a parametrised `<epidist>` is? Look at `?is_parameterised`.
added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/47148b9d6b88c8ad1b924aae101f1b17b8250037

2024-03-21 20:11 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +- Use `{epiparameter}` to access the systematic review catalogue of epidemiological delay distributions.
resolved in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/f6d1dbe3b4e2ae2f72d08ddb59bea07fabdab85d

2024-03-21 20:14 UTC, avallecam commented on episodes/delays-functions.Rmd
> +- How to connect reused delays with my existing analysis pipeline?
nice rephrase https://github.com/epiverse-trace/tutorials-early/pull/5/commits/73e77db7867f70d25eb78840fdd7b20cd1c62341

2024-03-21 20:19 UTC, avallecam commented on episodes/delays-functions.Rmd
> +**Epidemic theory** : Epidemiological parameters. Time periods.
updated in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/adc505508e453fb55103756e7722ce13293c4c47

2024-03-21 20:21 UTC, avallecam commented on episodes/delays-functions.Rmd
> +Now, we have an epidemiological parameter we can reuse! We can replace the **summary statistics** numbers we plug into `EpiNow2::dist_spec()`.
added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/9a7ec2ab4e996b47abdc326a8b8f78ebff97947e

2024-03-21 20:22 UTC, avallecam commented on episodes/delays-functions.Rmd
> +library(tidyverse)
I opt to make clear what operators and functions to use before loading packages. suggestion added in https://github.com/epiverse-trace/tutorials-early/pull/5/commits/22fe34c0bffe60ee72573e5422ffb880b2fb3aaf

2024-03-21 20:37 UTC, avallecam commented
Thank you for your review @joshwlambert! I managed to go through all your specific edit suggestions. I'll re-request your review for your assessment.

Here are replies to your questions.

> have you checked that all the images you are using from papers are allowed to be used with only attribution?

added in #12 to solve after this PR

> it would be good if you cited the papers mentioned using a bibliography and then provided a references section at the bottom of each page

sadly this is not possibly in the workbench (using bib files and @tags). I still do not know why, but I'll look forward to it. I'm already subscribed to some issues on it.

> Getting an {EpiNow2} developer to also check code chunks that use that package would be good

I'll do that! I'll homogenize the code with [quantify-transmission ](https://epiverse-trace.github.io/tutorials-middle/quantify-transmissibility.html) episode first.

2024-03-22 09:58 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +To exemplify how to use `{epiparameter}` in your analysis pipeline, our goal in this episode will be to *choose* one specific set of epidemiological parameters from the literature, instead of copy/pa
```suggestion
To exemplify how to use `{epiparameter}` in your analysis pipeline, our goal in this episode will be to *choose* one specific set of epidemiological parameters from the literature, instead of *copying-and-pasting* them by hand, to plug them into an `{EpiNow2}` analysis workflow.
```

2024-03-22 10:03 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +Let's start loading the `{epiparameter}` package. We'll use the pipe `%>%` to connect some of their functions, so let's also call to the `{magrittr}` package:
Getting error in challenge solution for `dplyr::distinct()`. Also using `tibble::as_tibble()` here, so better moving this back to {tidyverse}

```suggestion
Let's start loading the `{epiparameter}` package. We'll use the pipe `%>%` to connect some of their functions, some `{tibble}` and `{dplyr}` functions, so let's also call to the `{tidyverse}` package:
```

2024-03-25 12:44 UTC, joshwlambert commented on episodes/delays-reuse.Rmd
> +With this query combination, we get more than one delay distribution. This output is an object class `<multi_epidist>`.
I'm not sure the changes in 96d0ec8 are correct. If the output before was a `<multi_epidist>` this implies there was a list of `<epidist>` objects. It looks like the R code has not changed but the comments now state it is an `<epidist>`. Please check whether it is indeed an `<epidist>` or a list of `<epidist>` as this will matter for the user when working with these objects.

2024-03-25 12:55 UTC, joshwlambert approved these changes
@avallecam thanks for the changes. Everything looks good. I've unresolved one comment that I believe needs to be double checked. I haven't re-read through all the material, I just looked at the commits that resolve the comments. Feel free to request another review on a future PR if you'd like me to take another thorough look through all the material. 

> If we manage to render this locally, these two issues can be closed: https://github.com/epiverse-trace/tutorials/issues/39 and https://github.com/epiverse-trace/tutorials/issues/115

I'm having no issues rendering this branch (`add-read-delays`) locally on macOS, if this helps to close these issues.

2024-03-25 17:39 UTC, avallecam commented on episodes/delays-reuse.Rmd
> +library(magrittr)
```suggestion
library(tidyverse)
```

2024-03-25 17:53 UTC, merged