full review of tutorials-early
epiverse-trace/tutorials-early pull request #70
Opened 2024-05-04 09:18 UTC by avallecam

This PR aims to collect edit suggestions for the tutorials-early repository.

This includes any specific addition to:
- new episodes added on read, clean, validate, and aggregate data
- add content on epidemiological background or field applications
- add conceptual explanations of methods

All rendered content is in https://epiverse-trace.github.io/tutorials-early/

2024-05-27 12:38 UTC, Bisaloo commented on episodes/describe-cases.Rmd
> +title: 'Aggregate and visulaize'
```suggestion
title: 'Aggregate and visuliaze'
```

2024-06-04 10:07 UTC, Degoot-AM requested changes
@avallecam, I have a few comments on this PR, please review the changes.

2024-06-12 15:59 UTC, avallecam commented on .github/workflows/README.md
>  is stable. This is controlled by a single lockfile which documents the packages
interesting, this looks fixed in the [online file](https://github.com/epiverse-trace/tutorials-early/blob/main/.github/workflows/README.md#03-maintain-update-package-cache-update-cacheyaml)

2024-06-12 16:02 UTC, avallecam commented on config.yaml
> +title: 'Accessing and using delays to Quantify transmission'
seems to be fixed in https://github.com/epiverse-trace/tutorials-early/commit/d0d3b0857d82a588794c79375a84a3a0299e26cb

2024-06-12 16:06 UTC, avallecam commented on episodes/read-cases.Rmd
> +- Is it possible to import data from database and health APIs?
do you suggest this edit?
```suggestion
- Is it possible to import data from databases and health APIs? 
```

2024-06-12 16:14 UTC, avallecam commented on episodes/read-cases.Rmd
> +Similarly, you can import files of other formats such as `tsv`, `xlsx`, etc.
may the original one be clearer?

2024-06-12 16:16 UTC, avallecam commented on episodes/read-cases.Rmd
> +- Is it possible to read compressed data in `R`?
```suggestion

- Can you read data from a compressed file in `R`?
```

2024-06-12 16:26 UTC, avallecam commented on episodes/read-cases.Rmd
> +- Is it possible to read compressed data in `R`?
I suggest adding the text to download the file in this same line too.

```suggestion
Can you read data from a compressed file in `R`? Download this [zip file](https://epiverse-trace.github.io/tutorials-early/data/Marburg.zip) containing data for Marburg outbreak and then import it to your working environment.
```

2024-06-12 16:30 UTC, avallecam commented on episodes/read-cases.Rmd
> +Click [here](https://github.com/epiverse-trace/tutorials-early/tree/md-outputs-PR-39/data/Marburg.zip) to download a zip file containing data for Marburg outbreak  and then import it to your working
```suggestion
Click [here](https://epiverse-trace.github.io/tutorials-early/data/Marburg.zip) to download a zip file containing data for Marburg outbreak  and then import it to your working environment.
```

2024-06-12 16:33 UTC, avallecam commented on learners/setup.md
> +- <https://epiverse-trace.github.io/tutorials/data/ebola_cases.csv>
```suggestion
- <https://epiverse-trace.github.io/tutorials-early/data/ebola_cases.csv>
- <https://epiverse-trace.github.io/tutorials-early/data/Marburg.zip>
```

2024-06-13 17:08 UTC, avallecam commented on .github/workflows/README.md
>  is stable. This is controlled by a single lockfile which documents the packages
> This is controlled by a single lockfile, which documents versions of the packages
> needed for the lessons.

can you rephrase if there is an issue you identify with this? It is the workflow that can generate PR to update package versions in the [lockfile](https://github.com/epiverse-trace/tutorials-early/blob/main/renv/profiles/lesson-requirements/renv.lock)

2024-06-13 17:15 UTC, avallecam commented on episodes/clean-data.Rmd
> +- How to convert raw dataset into a `linelist` object?
is there any specific change proposed here?

2024-06-13 17:19 UTC, avallecam commented on episodes/clean-data.Rmd
> +**Exercise:** Standardize the column names of the input dataset, but keep the “V1” column as it is.
Could this also be within a callout box as challenge?

```suggestion
::::::::::::::::::::::::::::::::::::: challenge

Standardize the column names of the input dataset, but keep the “V1” column as it is.

::::::::::::::::::::::::::::::::::::::::::::::::
```

2024-06-14 01:05 UTC, avallecam reviewed
@Degoot-AM I finally managed to go through all the first four episodes! thank you work on them!

I prioritized code flow, that everything is running with the recent package versions. I found some edits required for cleanepi code, and one that I reported as issue.

Then I suggested to add some space between code lines within long chunks.

I added namespace reminders and some callout box of prerequisites as reminders of the dataset that we need to download before going through the episode.

For the first episode on read case data, we may open it to four subtitles to add brief details on each step. Also I suggested a figure as a first intro to databases.

Regarding the setup page, better if we focus to update the download links and the packages required for the four episodes. We had mixed and overlapping suggestions here and in the PR #64 so better if we reconciliate them after merging these most recent edits.

Are you able to approve commits in this PR? If yes, please, go ahead!

2024-06-14 01:05 UTC, avallecam commented on learners/setup.md
> +
```suggestion
# for episodes on read, clean, validate and visualize linelist
new_packages <- c(
  "epiverse-trace/cleanepi",
  "rio",
  "here",
  "DBI",
  "RSQLite",
  "dbplyr",
  "linelist",
  "epiverse-trace/simulist",
  "incidence2",
  "epiverse-trace/tracetheme",
  "tidyverse"
)

pak::pkg_install(new_packages)

# for episodes on access delays and quantify transmission
```

2024-06-14 01:09 UTC, avallecam commented on episodes/read-cases.Rmd
> +The following code chunk demonstrates how to create a temporary SQLite database in memory, store the `case_data` as a table on it, and subsequently read it:
```suggestion
The following code chunk demonstrates how to create a temporary SQLite database in memory, store the `ebola_confirmed` as a table on it, and subsequently read it:
```

2024-06-14 01:11 UTC, avallecam commented on episodes/read-cases.Rmd
> +ebola_confirmed <- read_csv(here::here("data", "raw-data", "ebola_cases.csv"))
this edit is related to https://github.com/epiverse-trace/tutorials-early/issues/73. I found this facilitates running the code.

2024-06-14 01:12 UTC, avallecam commented on episodes/read-cases.Rmd
> +
this is the source of figure https://jcsites.juniata.edu/faculty/rhodes/dbms/relnmodel.htm

2024-06-14 09:00 UTC, Degoot-AM reviewed
Thank you @avallecam for you feedback.

2024-06-14 09:02 UTC, Degoot-AM approved these changes

2024-06-14 20:54 UTC, avallecam commented on episodes/clean-data.Rmd
> +sim_ebola_data <- cleanepi::replace_missing_values(sim_ebola_data)
```suggestion
sim_ebola_data <- cleanepi::replace_missing_values(sim_ebola_data, na_strings = "")
```

2024-06-14 21:58 UTC, avallecam commented on .github/workflows/README.md
>  is stable. This is controlled by a single lockfile which documents the packages
since this file is a workflow file from the workbench infrastructure, better to propose edits in the [carpentries template file](https://github.com/carpentries/workbench-template-rmd/tree/main/.github/workflows)

2024-06-14 22:14 UTC, avallecam commented on episodes/clean-data.Rmd
> +- Demonstrate how to covert case data to `linelist` data
```suggestion
- Demonstrate how to covert case data to `linelist` data 
- Perform essential data-cleaning operations to address epidemiologically-related inconsistencies.
```

2024-06-14 22:15 UTC, avallecam commented on episodes/clean-data.Rmd
> +
added an edit suggestion of this in https://github.com/epiverse-trace/tutorials-early/pull/70/files#r1640396788

2024-06-17 16:45 UTC, avallecam commented on learners/setup.md
> +| Convert linelist data to incidence, access delay distributions, and estimate transmission metrics. | Forecast cases, estimate severity and  superspreading. | Simulate disease spread and investigate
```suggestion
| Read, clean and validate case data, convert linelist data to incidence for visualization. | Access delay distributions and estimate transmission metrics, forecast cases, estimate severity and superspreading. | Simulate disease spread and investigate interventions. |
```

2024-06-17 17:08 UTC, avallecam commented on episodes/read-cases.Rmd
> +## Reading from databases
placed as issue in #77

2024-06-17 17:11 UTC, avallecam commented on episodes/read-cases.Rmd
> +
as issue in #78

2024-06-17 17:13 UTC, avallecam commented on episodes/read-cases.Rmd
> +base::print(utils::head(result))
issue in #79

2024-06-17 17:28 UTC, avallecam commented on episodes/clean-data.Rmd
> +  cleanepi::replace_missing_values(target_columns = NULL) |>
```suggestion
  cleanepi::replace_missing_values(na_strings = "") |>
```

2024-06-17 18:53 UTC, avallecam commented
redirecting this PR to main now

2024-06-17 20:51 UTC, merged