add data validation step
epiverse-trace/tutorials-early pull request #95
Opened 2024-07-09 15:42 UTC by Degoot-AM

This PR adds data validation steps using the linelist package, addressing issue #92.

2024-07-29 20:29 UTC, avallecam requested changes
Thanks for the contribution @Degoot-AM!

This complementary content is appropriate to show the whole workflow of `{linelist}`: tag, validate, safeguard, and get a tagged-only data frame.

I think we can still work on the arrangement of this content to easily identify these four tasks.

For my edit suggestions, I suggest first incorporate the specific in-line edits and later the major content rearrangements:
- move the tags_df to the end
- add a challenge to test a different saveguard
- hide the tags_types output in a challenge hint to make this useful and not only descriptive
- simplify the showing of the validate functions

2024-07-29 20:29 UTC, avallecam commented on episodes/clean-data.Rmd
> +
here I would add a challenge to test the complementary message of error and invite learners to identify how it changes the output and workflow downstream

```r
linelist::lost_tags_action(action = "error")
```

2024-07-29 20:29 UTC, avallecam commented on episodes/clean-data.Rmd
> +```
I would move this as a hint in a challenge right after using `linelist::make_linelist()`. The output is long and more relevant when the learner is challenged to tag a different set of variables

2024-07-29 20:29 UTC, avallecam commented on episodes/clean-data.Rmd
> +```
I would move this to the end. This will help to keep the following sequence of steps: tag, safeguarding, validate, and then use tagged-only columns downstream.

2024-07-29 20:29 UTC, avallecam commented on episodes/clean-data.Rmd
> +`allow_extra = TRUE` when creating the linelist object.
instead of showing both functions, we can only show one `linelist::validate_linelist()` which embeds them ([check the function definition](https://github.com/epiverse-trace/linelist/blob/main/R/validate_linelist.R#L62-L70)).

We can make a subset from the raw data and provide an accidental tagging of a non-completely cleaned dataset, similar to:

```r
linelist::make_linelist(
  x = cleaned_data,
  id = "case_id",
  age = "gender" # accidental tagging
) %>% 
  linelist::validate_linelist()
```

possibly similar to a challenge.

2024-07-30 08:44 UTC, avallecam commented on episodes/clean-data.Rmd
> +
before leaving the episode I think we can add a callout box called "When should I use `{linelist}`?" that redirects learners to the get started vignette. This is critical, given that `linelist` is more appropriate for ongoing/long-lasting analysis than historical/quick analysis.

2024-07-30 09:55 UTC, avallecam commented on episodes/clean-data.Rmd
> +`allow_extra = TRUE` when creating the linelist object.
As a last resource, I think it appropriate to show two additional concepts, possibly in a hidden callout after a challenge or similar:
- how to add extra tags? with the `allow_extra = TRUE` argument
- how to validate these extra tags? by defining their specific `tags_types()`.

``` r
library(outbreaks)
library(tidyverse)
library(linelist)

# cleaned data
ebola <- outbreaks::ebola_sim_clean %>% 
  pluck("linelist") %>% 
  as_tibble()

# tag data
ebola_tag <- ebola %>% 
  make_linelist(
    id = "case_id",
    date_onset = "date_of_onset",
    gender = "gender"
  )

tags(ebola_tag)
#> $id
#> [1] "case_id"
#> 
#> $date_onset
#> [1] "date_of_onset"
#> 
#> $gender
#> [1] "gender"

# validate_linelist(ebola_tag)

# tag extra columns
ebola_tag_02 <- ebola %>% 
  make_linelist(
    id = "case_id",
    date_onset = "date_of_onset",
    gender = "gender",
    generation_number = "generation", allow_extra = TRUE
  )

tags(ebola_tag_02)
#> $id
#> [1] "case_id"
#> 
#> $date_onset
#> [1] "date_of_onset"
#> 
#> $gender
#> [1] "gender"
#> 
#> $generation_number
#> [1] "generation"


# validate rejects
validate_linelist(
  x = ebola_tag_02,
  allow_extra = TRUE,
  ref_types = tags_types(
    generation_number = c("character"), # if "integer", validation success
    allow_extra = TRUE
  )
)
#> Error: Some tags have the wrong class:
#>   - generation_number: Must inherit from class 'character', but has class 'integer'
```

<sup>Created on 2024-07-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

2024-07-30 10:12 UTC, avallecam commented on episodes/clean-data.Rmd
> +```
and emphasize using a combination `dplyr::glimpse` with  `linelist::tags_names` to write new tags

2024-07-30 13:58 UTC, avallecam commented
I think the main theme in this episode could be that "we need clean data to allow appropriate tagging and validation before running the analysis"

2024-08-01 10:38 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +new_df <- data |> dplyr::select(linelist::has_tag(c("id", "age")))
Good. Will add it

2024-08-01 10:40 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +
Will add  a challenge

2024-08-01 11:06 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +new_df <- data |> dplyr::select(linelist::has_tag(c("id", "age")))
accept it

2024-08-01 11:37 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +
OK. Will add a callout.

2024-08-01 12:07 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +```
Ok. Will fix it.

2024-08-01 12:21 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +```
OK. Will move it down.

2024-08-01 12:48 UTC, Degoot-AM commented on episodes/clean-data.Rmd
> +`allow_extra = TRUE` when creating the linelist object.
OK. I have added.

2024-09-05 17:29 UTC, avallecam requested changes
Thanks @Degoot-AM for this modifications. This looks good!

I tested it as a learner. From this, I suggested using the simplest pieces of code to learn about the {linelist} outputs. Also suggested some text edits to make the content more readable. Lastly, I provided my longest edits to the challenges given that we can provide "formative assessments" based on code that could produce these moments of "oh! this has changed!" and then the learning, as is the approach you are following.

Note: some code solutions are in bullets on purpose to allow its writing. If accepted, will be removed #106 

This is my last request for changes, I promise :D

2024-09-05 17:29 UTC, avallecam commented on episodes/clean-data.Rmd
> +datatype.
Given that tagging and validating a new tag needs using `make_linelist()`, `validate_linelist()`, and `tags_types()`. Probably better to keep it outside in the how-to guides.

I will share a PR on howto repo after this review. For the moment, we can block this sentences:

```suggestion
<!-- If your dataset requires a new tag, set the argument -->
<!-- `allow_extra = TRUE` when creating the linelist object with its corresponding-->
<!-- datatype. -->
```

2024-09-05 17:29 UTC, avallecam commented on episodes/clean-data.Rmd
> +:::::::::::::::::::::::::
As mentioned in the previous comment, we can tackle those questions and provide a solution redirecting learners to the howto repo. 

Instead, I'm providing an exploratory challenge:

```suggestion
::::::::::::::::::::::::: challenge

Let's change some variable data types to identify how `linelist::validate_linelist()` will react when your input data has a variable with a different data type.

Try to:

- **Change** a variable data type,
- **Tag** the linelist, and then 
- **Validate** it

Identify the correlation between the error messages and the output of `linelist::tags_types()`.

:::::::::::::::::::::::::: hint

If we change the `age` variable from numeric to character:

- `cleaned_data %>%`
- `# change data type`
- `mutate(age_character = as.character(age)) %>%`
- `# tag`
- `linelist::make_linelist(`
- `  age = "age_character"`
- `) %>%`
- `# validate`
- `linelist::validate_linelist()`

Other frequent changes can be having a date variable like `date_onset` changed to a character, or a factor variable like `gender` changed to an integer.

::::::::::::::::::::::::::

::::::::::::::::::::::::: hint

- `# example 2`
- `cleaned_data %>% `
-   `# mess`
-   `mutate(date_onset_character = as.character(date_onset)) %>% `
-   `# tag`
-   `linelist::make_linelist(`
-     `date_onset = "date_onset_character"`
-   `) %>% `
-   `# validate`
-   `linelist::validate_linelist()`

- `# example 3`
- `cleaned_data %>% `
-   `# mess`
-   `mutate(gender = as.factor(gender)) %>% `
-   `mutate(gender_integer = as.integer(gender)) %>% `
-   `# tag`
-   `linelist::make_linelist(`
-     `gender = "gender_integer"`
-   `) %>% `
-   `# validate`
-   `linelist::validate_linelist()`

::::::::::::::::::::::::: 

:::::::::::::::::::::::::
```

2024-09-05 17:29 UTC, avallecam commented on episodes/clean-data.Rmd
> +This allows, the extraction of use tagged-only columns in downstream analysis.
```suggestion
This allows, the extraction of use tagged-only columns in downstream analysis, which will be useful for the next episode!
```

2024-09-10 17:50 UTC, Degoot-AM reviewed
Accepting changes proposed by @avallecam.

2024-09-12 16:59 UTC, avallecam approved these changes
Thanks for accepting the feedback edits. I added some extra commits to clarify some lines I suggested. Now ready to merge 🚀

2024-09-13 08:44 UTC, avallecam commented
I'm solving now the conflicts to merge this briefly.

2024-09-13 09:15 UTC, merged